### PR TITLE
make Italian note in readme more inviting

### PR DESCRIPTION
**Pull request by Pandademic**
⬆️

### CODE REVIEW

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I'd actually been thinking about fixing that grammatical error, so thanks for beating me to it, @Pandademic!

**Comment by Pandademic** [comment]
@RandomDSdevel I really like the idea of this project , and contributing was the least I could do.I suck at C I'll try and contribute to doc's!

**Comment by Pandademic** [comment]
@RandomDSdevel hahahaha thanks

**Comment by amuno34** [comment]
> ⬆️

Thanks for fixing it! <3
(yep I'm the one who did the original translation)

**Pull request merged**
